version: 2.1

executors:
  golang-ci:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.12


commands:
  setup_env:
    parameters:
      environment:
        type: string
        default: "dev"
    steps:
      - run:
          name: "Setup the environment << parameters.environment >>"
          command: |
            echo  << parameters.environment >>
  deploy_env:
    parameters:
      environment:
        type: string
        default: "dev"
      seconds:
        type: string
        default: "5"
    steps:
      - run:
          name: "Deploy to environment << parameters.environment >>"
          command: |
            sleep << parameters.seconds >>
            echo  << parameters.environment >>

jobs:
  build:
    executor: golang-ci
    steps:
      - checkout
      - run:
          name: Build Code
          command:  |
            sleep 10
            echo "Build Done"


  deploy:
    executor: golang-ci
    steps:
      - checkout
      - setup_env
      - deploy_env

  deploy-staging:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_env:
          environment: staging
      - deploy_env:
          environment: staging
          seconds: "10"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only:
                - /^staging.*/
