version: 2.1
orbs:
  slack: circleci/slack@2.4.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout
      - run:
          name: Build Code
          command:  |
            sleep 10
            echo "Build Done"

  deploy:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Setup Env
          command:  |
            sleep 4
            echo "Setup Dev Environment"
      - run:
          name: Deploy to Dev
          command:  |
            sleep 4
            echo "Deploy to Dev Environment"

  deploy-staging:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Setup Env
          command:  |
            sleep 4
            echo "Setup Staging Environment"
      - run:
          name: Deploy to Dev
          command:  |
            sleep 4
            echo "Deploy to Staging Environment"


workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only:
                - /^staging.*/
